Feature/gsagive 136 - HMAC digital signature generation - WIP
18F/identity-give-api-gateway pull request #5
Opened 2020-09-29 16:06 UTC by pshumateEDC

Add javacsript file containing code for the generation of a hmac digital signature that complies with Kong's specifications. Adjust the readme file to describe the process of using it accordingly.

2020-10-08 15:05 UTC, pkothare requested changes
Needs an integration test and slight restructuring of the README contents.

2020-10-08 15:05 UTC, pkothare commented on post-deployment.sh
> +curl -X POST http://localhost:80/plugins/ --data "name=hmac-auth" -d "config.enforce_headers=date, request-line" &
While this configures HMAC Auth, we also need an integration test as a confirming step, which is not present in the pull request. Please add the test accordingly.

The test should fetch the current configuration for the deployed instance and ensure that the desired HMAC configuration is present in the JSON.

2020-10-16 16:26 UTC, pshumateEDC commented on README.md
> +- [Postman](https://www.postman.com/downloads/)
Removed Postman references from README

2020-10-16 16:27 UTC, pshumateEDC commented on README.md
> +### Making an Authenticated Request (in Postman)
New README exists in `tests/`

2020-10-16 16:27 UTC, pshumateEDC commented on post-deployment.sh
> +curl -X POST http://localhost:80/plugins/ --data "name=hmac-auth" -d "config.enforce_headers=date, request-line" &
Python integration tests now exist in `tests/`.

2020-10-16 16:33 UTC, pshumateEDC commented
Current state of application in cloud foundry:
```
11:15:07.509: [STG.0] -----> Adding apt repos
11:15:07.509: [STG.0] Added repo {deb https://kong.bintray.com/kong-deb bionic main }
11:15:07.509: [STG.0] -----> Updating apt cache
11:18:31.805: [STG.0]        **ERROR** Error running supply: failed to apt-get update Ign:1 https://kong.bintray.com/kong-deb bionic InRelease
11:18:31.805: [STG.0]        Get:2 https://kong.bintray.com/kong-deb bionic Release [3,524 B]
11:18:31.805: [STG.0]        Get:3 https://kong.bintray.com/kong-deb bionic Release.gpg [821 B]
11:18:31.805: [STG.0]        Get:4 https://kong.bintray.com/kong-deb bionic/main amd64 Packages [4,210 B]
11:18:31.805: [STG.0]        Err:4 https://kong.bintray.com/kong-deb bionic/main amd64 Packages
11:18:31.805: [STG.0]          File has unexpected size (4294 != 4210). Mirror sync in progress? [(IP hidden)]
11:18:31.805: [STG.0]          Hashes of expected file:
11:18:31.805: [STG.0]           - Filesize:4210 [weak]
11:18:31.805: [STG.0]           - SHA256:054ea01d5de35adf9c8aa65559c2d9cb2f40349e70a8ddd0ad625fe1f18e6ba1
11:18:31.805: [STG.0]           - SHA1:c80b403a6d6f74216d98854b1d9698c2051b461f [weak]
11:18:31.805: [STG.0]           - MD5Sum:0e1f7ea048f175a83335c8a19790bee9 [weak]
11:18:31.805: [STG.0]          Release file created at: Thu, 01 Oct 2020 14:34:21 +0000
11:18:31.805: [STG.0]        Get:5 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
11:18:31.805: [STG.0]        Get:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
11:18:31.805: [STG.0]        Get:7 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
11:18:31.805: [STG.0]        Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]
11:18:31.805: [STG.0]        Get:9 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
11:18:31.805: [STG.0]        Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
11:18:31.805: [STG.0]        Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,112 kB]
11:18:31.805: [STG.0]        Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [45.5 kB]
11:18:31.805: [STG.0]        Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,150 kB]
11:18:31.805: [STG.0]        Get:14 http://archive.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [15.0 kB]
11:18:31.805: [STG.0]        Get:15 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,348 kB]
11:18:31.805: [STG.0]        Get:16 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1,733 kB]
11:18:31.805: [STG.0]        rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
11:18:31.805: [STG.0]        Fetched 20.7 MB in 3min 23s (102 kB/s)
11:18:31.805: [STG.0]        Reading package lists...
11:18:31.805: [STG.0]        E: Failed to fetch https://kong.bintray.com/kong-deb/dists/bionic/main/binary-amd64/Packages.gz  File has unexpected size (4294 != 4210). Mirror sync in progress? [IP: 52.88.32.158 443]
11:18:31.805: [STG.0]           Hashes of expected file:
11:18:31.805: [STG.0]            - Filesize:4210 [weak]
11:18:31.805: [STG.0]            - SHA256:054ea01d5de35adf9c8aa65559c2d9cb2f40349e70a8ddd0ad625fe1f18e6ba1
11:18:31.805: [STG.0]            - SHA1:c80b403a6d6f74216d98854b1d9698c2051b461f [weak]
11:18:31.805: [STG.0]            - MD5Sum:0e1f7ea048f175a83335c8a19790bee9 [weak]
11:18:31.805: [STG.0]           Release file created at: Thu, 01 Oct 2020 14:34:21 +0000
11:18:31.805: [STG.0]        E: Some index files failed to download. They have been ignored, or old ones used instead.
11:18:31.805: [STG.0]        
11:18:31.805: [STG.0]        
11:18:31.805: [STG.0]        exit status 100
```

2020-11-30 19:07 UTC, closed without merging