add network policies for sk services
18F/identity-give-api-gateway pull request #59
Opened 2021-06-23 17:48 UTC by dzaslavskiy

2021-06-23 18:27 UTC, folksgl requested changes

2021-06-23 18:27 UTC, folksgl commented on .github/workflows/deploy.yaml
>            cf add-network-policy api-gateway usps
These should be removed, yes?

2021-06-23 18:30 UTC, dzaslavskiy commented on .github/workflows/deploy.yaml
>            cf add-network-policy api-gateway usps
Not sure. Have we finalized that?

2021-06-23 19:23 UTC, folksgl commented on .github/workflows/deploy.yaml
>            cf add-network-policy api-gateway usps
Yes. All integrations will go through SK, so the only routes available from the API gateway should be to SK.

2021-06-23 20:42 UTC, folksgl approved these changes

2021-06-24 14:06 UTC, folksgl approved these changes

2021-06-24 15:31 UTC, merged